# Generated by Django 4.2.7 on 2023-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("estrelas", models.IntegerField(default=0)),
            ],
        ),
    ]
