# Generated by Django 4.2.7 on 2023-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MinhaMensagem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("quantidade", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="mensagem", name="data_envio",),
        migrations.AddField(
            model_name="mensagem",
            name="estrelas",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mensagem", name="texto", field=models.CharField(max_length=255),
        ),
    ]
